#!/bin/bash

set -eo pipefail

if [ -z "$ENV_FILE" ]; then
    echo "ENV_FILE not set"
    exit 1
fi

if [ -f "$ENV_FILE" ]; then
    echo "loading .env..."
    set -a
    source "$ENV_FILE"
    set +a
fi

if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ] || [ -z "$DB_NAME" ]; then
    echo "one or more required env vars are not set. aborting..."
    exit 1
fi

if [ -n "$ADMIN_PASSWORD_REQUIRED" ]; then
    if [ -z "$ADMIN_PASSWORD_HASH" ]; then
        echo "ADMIN_PASSWORD_HASH not set. aborting..."
        exit 1
    fi
fi

echo "env vars loaded"
echo
