#!/bin/sh

set -e

echo "Running pre-commit hook..."
echo

echo "Scanning for secrets in staged files..."
ggshield secret scan pre-commit "$@"
echo

echo "Formatting and linting staged files..."
lint-staged
echo

echo "Checking shared project version..."
./scripts/check-shared-version.sh
echo

echo "Checking for knip issues..."
knip
echo

echo "Checking for available updates..."
echo "Checking base project..."
ncu
echo

echo "Checking shared project..."
ncu --cwd shared --configFilePath shared/.ncurc.json
echo

echo "Checking client project..."
ncu --cwd client --configFilePath client/.ncurc.json
echo

echo "Checking server project..."
ncu --cwd server --configFilePath server/.ncurc.json
echo

echo "Done running pre-commit hook"
